-- ANNOUNCEMENT table for admin announcements (#12)
CREATE SEQUENCE ANNOUNCEMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE ANNOUNCEMENT (
    ID NUMBER DEFAULT ANNOUNCEMENT_SEQ.NEXTVAL PRIMARY KEY,
    ADMIN_ID NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    TARGET_ROLE VARCHAR2(20) DEFAULT 'ALL' NOT NULL,
    IS_PINNED NUMBER(1) DEFAULT 0 NOT NULL,
    VIEW_COUNT NUMBER DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_ANNOUNCEMENT_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES USERS(ID),
    CONSTRAINT CHK_ANNOUNCEMENT_ROLE CHECK (TARGET_ROLE IN ('ALL', 'CUSTOMER', 'BOOK_OWNER'))
);
