-- POST_LIKE table: Post like (heart) system
-- Run this on the actual database to enable the like feature

CREATE TABLE POST_LIKE (
    ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    POST_ID    NUMBER        NOT NULL,
    USER_ID    NUMBER        NOT NULL,
    CREATED_AT TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_PL_POST
        FOREIGN KEY (POST_ID)
        REFERENCES BOOK_OWNER_POST (ID),

    CONSTRAINT FK_PL_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS (ID),

    CONSTRAINT UQ_PL_POST_USER
        UNIQUE (POST_ID, USER_ID)
);

-- After creation, find the identity sequence:
-- SELECT SEQUENCE_NAME FROM ALL_TAB_IDENTITY_COLS WHERE TABLE_NAME = 'POST_LIKE';
-- Then update PostLikeMapper.xml: replace ISEQ$$_XXXXX with the actual sequence name
